export const excelHeaderMap = [
  // { title: '学籍号', key: 'cardId'},
  // { title: '学号', key: 'classId'},
  // { title: '姓名', key: 'name'},
  // { title: '年龄', key: 'age'},
  // { title: '年级', key: 'grade'},
  // { title: '班级', key: 'classNum'},
  // { title: '性别', key: 'sex'},
  // { title: '类别', key: 'type'},
  // { title: '手机号（非必填）', key: 'telPhone'},
  // { title: '省份', key: 'province'},
  // { title: '民族', key: 'nation'},
  // { title: '家长知情同意（是/否）', key: 'known'},

  // 
  { title: 'id', key: 'id'},
  { title: '名称', key: 'name'},
  { title: '形象', key: 'animal'},
  { title: '色相', key: 'hue'},
  { title: '色调', key: 'stripe'},
  { title: '开放度', key: 'open'},
  { title: '理性', key: 'sense'},
  { title: '个人特质', key: 'person'},
  { title: '内认同——外认同', key: 'rentong'},
  { title: '理性——感性', key: 'lixing'},
  { title: '个体——群体', key: 'geti'},
  { title: '执行——幻想', key: 'zhixing'},
  { title: '果断——谨慎', key: 'guoduan'},
  { title: '现实——理想', key: 'xianshi'},
  { title: '学习风格', key: 'study'},
  { title: '沟通方式（父母或老师）', key: 'communicate'},
  { title: '人际关系（同龄朋友）', key: 'interpersonal'},
];